import React from "react";
import { Metadata } from "next";
import TopBar from "@/components/TopBar";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import InteractivePlaneWorldMap from "@/components/InteractivePlaneWorldMap";
import { Briefcase, Key, HelpCircle, ShieldAlert, CheckSquare } from "lucide-react";

export const metadata: Metadata = {
  title: "Work Visa & Skilled Worker Relocation Services | VisaEnsure",
  description: "Relocate abroad with expert work visa assistance. Learn about H-1B, UK Skilled Worker, German Opportunity Card, and Australian 482 sponsorship.",
  keywords: ["work visa", "skilled worker visa", "H1B visa", "UK work permit", "Chancenkarte", "employer sponsorship", "jobs abroad"],
};

export default function WorkVisaPage() {
  return (
    <div className="flex flex-col min-h-screen bg-white text-ink-900 overflow-hidden">
      <TopBar />

      {/* Header / Intro section */}
      <main className="flex-1 py-12 md:py-16 relative">
        {/* Decorative Background Elements */}
        <div className="absolute top-[10%] left-[20%] w-[300px] h-[300px] bg-orange-600/5 blur-[120px] pointer-events-none" />
        <div className="absolute bottom-[20%] right-[10%] w-[450px] h-[450px] bg-orange-600/5 rounded-full blur-[80px] pointer-events-none" />

        <div className="max-w-7xl mx-auto px-4 md:px-8 space-y-12">
          {/* Hero Header */}
          <div className="space-y-4 text-center max-w-3xl mx-auto">
            <span className="eyebrow">
              Work & Relocation Programs
            </span>
            <h1 className="t-display text-ink-900">
              International Skilled Employment Permits
            </h1>
            <span className="accent-bar mx-auto" />
            <p className="t-lead">
              Analyze in-demand job markets and switchable visa pathways. Click on highlighted countries on the flat map below to view average salaries and eligibility requirements.
            </p>
          </div>

          {/* Interactive Map Component */}
          <section className="card p-4 md:p-8">
            <InteractivePlaneWorldMap visaType="work" />
          </section>

          {/* Core Support Areas */}
          <section className="grid grid-cols-1 md:grid-cols-3 gap-6 pt-6">
            {[
              {
                icon: <Briefcase className="w-6 h-6 text-orange-600" />,
                title: "Employer Sponsorship Auditing",
                desc: "We verify whether your sponsoring employer is licensed, check salary thresholds against national standards, and double-check occupational codes."
              },
              {
                icon: <Key className="w-6 h-6 text-orange-600" />,
                title: "Opportunity Card Points Verification",
                desc: "Comprehensive pre-evaluation for points-based job search pathways like Germany's Chancenkarte, ensuring positive assessment outcomes."
              },
              {
                icon: <CheckSquare className="w-6 h-6 text-orange-600" />,
                title: "Dependent Concurrence Filing",
                desc: "Simultaneous processing of spousal open work permits and child study permits so your family relocates with you together."
              }
            ].map((item, idx) => (
              <div key={idx} className="card card-hover p-6 space-y-3 group">
                <div className="w-11 h-11 bg-orange-50 border border-orange-100 rounded-xl flex items-center justify-center transition-transform duration-300 group-hover:scale-110">
                  {item.icon}
                </div>
                <h3 className="t-h4 text-ink-900">{item.title}</h3>
                <p className="t-body text-[0.8125rem]">{item.desc}</p>
              </div>
            ))}
          </section>

          {/* Quick FAQ Block */}
          <section className="space-y-6 pt-6 border-t border-ink-100">
            <h2 className="t-h2 text-ink-900 text-center">Frequently Asked Questions</h2>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              {[
                {
                  q: "What is a Certificate of Sponsorship (CoS)?",
                  a: "A CoS is an electronic record generated by UK employers holding an A-rated sponsor licence, confirming details of the job role and salary offered to you."
                },
                {
                  q: "Can I move to Germany without a job offer?",
                  a: "Yes, under the new Opportunity Card (Chancenkarte) system, skilled professionals scoring at least 6 points can enter Germany for up to 12 months to seek qualified work."
                }
              ].map((faq, i) => (
                <div key={i} className="card p-5 space-y-2">
                  <h4 className="t-h4 text-ink-900 flex items-start gap-2">
                    <HelpCircle className="w-4.5 h-4.5 text-orange-600 shrink-0 mt-0.5" />
                    <span>{faq.q}</span>
                  </h4>
                  <p className="t-body text-[0.8125rem] pl-6">{faq.a}</p>
                </div>
              ))}
            </div>
          </section>
        </div>
      </main>

      <Footer />
    </div>
  );
}
